<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2342" started-at="2015-12-17T09:33:54Z" finished-at="2015-12-17T09:33:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2342" started-at="2015-12-17T09:33:54Z" finished-at="2015-12-17T09:33:56Z">
      <class name="com.yumendedao.test.TestAbstractPaging">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.yumendedao.test.TestAbstractPaging@3ff9ddb5]" name="beforeClass" is-config="true" duration-ms="10" started-at="2015-12-17T17:33:54Z" finished-at="2015-12-17T17:33:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testAbstractPaging()[pri:0, instance:com.yumendedao.test.TestAbstractPaging@3ff9ddb5]" name="testAbstractPaging" duration-ms="2304" started-at="2015-12-17T17:33:54Z" finished-at="2015-12-17T17:33:56Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:604)
	at java.util.ArrayList.get(ArrayList.java:382)
	at com.yumendedao.abstracts.AbstractPaging.removeFootBlank(AbstractPaging.java:150)
	at com.yumendedao.abstracts.AbstractPaging.addData(AbstractPaging.java:30)
	at com.yumendedao.test.TestAbstractPaging.testAbstractPaging(TestAbstractPaging.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAbstractPaging -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.yumendedao.test.TestAbstractPaging@3ff9ddb5]" name="afterClass" is-config="true" duration-ms="1" started-at="2015-12-17T17:33:56Z" finished-at="2015-12-17T17:33:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.yumendedao.test.TestAbstractPaging -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
